# Use root/example as user/password credentials
version: '3.1'

services:
  mariadb:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: mariadb
    environment:
      - TZ=Etc/UTC
      - MYSQL_ROOT_PASSWORD=ROOT_ACCESS_PASSWORD
    ports:
      - 3306:3306
    restart: unless-stopped